# Import package
# Import package
import re
import wikipedia # Specify the title of the Wikipedia page


list_of_articles = ['Carcinoma of Unknown Primary',
'Cardiac Tumors',
'Central Nervous System',
'Atypical Teratoid',
'Rhabdoid Tumor',
'Germ Cell Tumor',
'Primary CNS Lymphoma',
'Cervical Cancer',
'Childhood Cancers',
'Cancers of Childhood',
'Cholangiocarcinoma',
'Chordoma',
'Chronic Lymphocytic Leukemia',
'Chronic Myelogenous Leukemia',
'Chronic Myeloproliferative Neoplasms',
'Colorectal Cancer',
'Craniopharyngioma',
'Cutaneous T-Cell Lymphoma',
'Ductal Carcinoma In Situ',
'Embryonal Tumors',
'Medulloblastoma',
'Endometrial Cancer',
'Ependymoma',
'Esophageal Cancer',
'Esthesioneuroblastoma',
'Ewing Sarcoma',
'Extracranial Germ Cell Tumor',
'Extragonadal Germ Cell Tumor',
'Eye Cancer',
'Intraocular Melanoma',
'Retinoblastoma',
'Fallopian Tube Cancer',
'Fibrous Histiocytoma of Bone',
'Gallbladder Cancer',
'Gastrointestinal Carcinoid Tumor',
'Gastrointestinal Stromal Tumors',
'Germ Cell Tumors',
'Germ Cell Tumors',
'Childhood Extracranial Germ Cell Tumors',
'Extragonadal Germ Cell Tumors',
'Ovarian Germ Cell Tumors',
'Testicular Cancer',
'Gestational Trophoblastic Disease',
'Hairy Cell Leukemia',
'Heart Tumors',
'Hepatocellular Cancer',
'Histiocytosis, Langerhans Cell',
'Hodgkin Lymphoma',
'Hypopharyngeal Cancer',
'Pancreatic Neuroendocrine Tumors',
'Langerhans Cell Histiocytosis',
'Laryngeal Cancer',
'Leukemia',
'Liver Cancer',
'Non-Small Cell Lung Cancer',
'Small Cell Lung Cancer',
'Pleuropulmonary Blastoma',
'Tracheobronchial Tumor',
'Male Breast Cancer',
'Malignant Fibrous Histiocytoma',
'Melanoma',
'Intraocular Melanoma',
'Merkel Cell Carcinoma (Skin Cancer)',
'Mesothelioma, Malignant',
'Metastatic Cancer',
'Midline Tract Carcinoma',
'Multiple Endocrine Neoplasia Syndromes',
'Multiple Myeloma/Plasma Cell Neoplasms',
'Myelodysplastic Syndromes',
'Myelodysplastic',
'Myeloproliferative Neoplasms',
'Chronic Myelogenous Leukemia',
'Acute Myeloid Leukemia',
'Myeloproliferative Neoplasms, Chronic',
'Nasal Cavity',
'Paranasal Sinus Cancer',
'Nasopharyngeal Cancer',
'Neuroblastoma',
'Non-Hodgkin Lymphoma',
'Non-Small Cell Lung Cancer',
'Oral Cancer',
'Lip Cancer',
'Oropharyngeal Cancer',
'Oral Cavity Cancer',
'Osteosarcoma',
'Undifferentiated Pleomorphic Sarcoma of Bone Treatment',
'Ovarian Cancer',
'Pancreatic Cancer',
'Pancreatic Neuroendocrine Tumors',
'Islet Cell Tumors',
'Papillomatosis',
'Paraganglioma',
'Paranasal Sinus Cancer',
'Nasal Cavity Cancer',
'Parathyroid Cancer',
'Penile Cancer',
'Pharyngeal Cancer',
'Pheochromocytoma',
'Pituitary Tumor',
'Plasma Cell Neoplasm',
'Multiple Myeloma',
'Pleuropulmonary Blastoma'
'Lung Cancer',
'Primary Central Nervous System ',
'CNS Lymphoma',
'Primary Peritoneal Cancer',
'Prostate Cancer',
'Rare Cancers of Childhood',
'Rectal Cancer',
'Recurrent Cancer',
'Renal Cell Cancer',
'Retinoblastoma',
'Rhabdomyosarcoma',
'Salivary Gland Cancer', 
'Sarcoma',
'Childhood Rhabdomyosarcoma',
'Childhood Vascular Tumors',
'Ewing Sarcoma',
'Bone Cancer',
'Kaposi Sarcoma',
'Osteosarcoma',
'Soft Tissue Sarcoma',
'Uterine Sarcoma'
'Sézary Syndrome',
'Lymphoma',
'Skin Cancer',
'Small Cell Lung Cancer',
'Small Intestine Cancer',
'Soft Tissue Sarcoma',
'Squamous Cell Carcinoma of the Skin',
'Skin Cancer',
'Squamous Neck Cancer ',
'Metastatic Head and Neck Cancer',
'Stomach Cancer',
'Gastric Cancer',
'T-Cell Lymphoma',
'Mycosis Fungoides',
'Sèzary Syndrome',
'Testicular Cancer',
'Head and Neck Cancer',
'Nasopharyngeal Cancer',
'Oropharyngeal Cancer',
'Hypopharyngeal Cancer',
'Thymoma ',
'Thymic Carcinoma',
'Thyroid Cancer',
'Tracheobronchial Tumors (Lung Cancer)',
'Transitional Cell Cancer of the Renal Pelvis ',
'Kidney cancer',
'Unknown Primary, Carcinoma of',
'Ureter Cancer',
'Renal Pelvis',
'Transitional Cell Cancer',
'Urethral Cancer',
'Uterine Cancer',
'Uterine Sarcoma',
'Vaginal Cancer',
'Soft Tissue Sarcoma',
'Vulvar Cancer',
'Wilms Tumor'
'Cat',
'Dog',
'animal',
'car',
'locomotive',
'jet engine',
'transportation',
'diabetes',
'atrial fibrillation',
'hypertension',
'myocardial infarction',
'coronary artery disease',
'cholesterol',
'hyperlipidemia',
'organism',
'medicine',
'internal medicine',
'cardiology',
'pulmonology',
'oncology',
'hematology',
'nephrology',
'infectious disease',
'rheumatology',
'body organs',
'disease',
'tobacco',
'COPD',
'pneumonia',
'respiratory failure',
'cardiac arrest',
'dog',
'cat',
'disease',
'healthcare',
'immune system',
'pathology',
'amlodipine',
'hydrochlorothiazide',
'carvedilol',
'metoprolol',
'doxorubucin',
'escitalopram',
'albuterol',
'budesonide',
'glaucoma',
'tinnitis',
'bradycardia',
'insulin',
'januvia',
'metformin',
'sitagliptin',
'atorvastatin',
'rosuvastatin',
'norepinephrine',
'levophed',
'midazolam',
'rocuronium',
'jet engine',
'internal combustion engine',
'external combustion engine',
'electric motor',
'hansel and gretel',
'beowulf',
'iliad',
'odyssey',
'little red riding hood',
'the hobbit',
'harry potter',
'dragonlance',
'green',
'blue',
'red',
'yellow',
'apple',
'pear',
'orange',
'watermelon',
'cactus',
'sequoia (genus)'
'evergreen',
'tesla',
'ford',
'abies alba'
'atherosclerosis'
'diet',
'healthy diet',
'veganism',
'cochrane review',
'occupational health',
'randomized control trial',
'observational studies',
'health economics',
'evidenced-based medicine',
'systematic review'

]

list_of_text = []

for count, article in enumerate(list_of_articles):
	print (article)

	try:

		wiki = wikipedia.page(article)# Extract the plain text content of the page
		text = wiki.content
		text = re.sub(r'==.*?==+', '', text)
		text = text.replace('\n', '')
		list_of_text.append(text)
	except:
		print ('your article'+article+'was not found.')


for count,text2 in enumerate(list_of_text):
	filename = './wiki_output/wiki_output_'+str(count)+'.txt'
	with open(filename, "w") as text_file:
		string_text = str(text2)
		text_file.write(string_text)
		print(string_text)

					



# your articleMidline Tract Carcinomawas not found.
# your articleTracheobronchial Tumors (Lung Cancer)was not found.
